language: php

php:
  - 5.6
  - 7
  - hhvm

sudo: false

install:
  - composer install --no-interaction

script:
  - make test

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/coveralls -v; fi
